### ISSUE TITLE
Add comments API call

### ISSUE THREAD

**Issue by tatirajurishabh** [RTX2080-UF/gatorshare-frontend#55]
Comments currently load demo data, move this to REST call.

**Comment by tatirajurishabh** [comment]
Comments API is misbehaving, hence moving this to the next sprint and marking as blocked

**Comment by tatirajurishabh** [comment]
@R3dIO wanted to know if the comments API has been fixed or would you need more time to implement this? Currently, the API is not sending the comments of the post.

**Comment by R3dIO** [comment]
It's fixed but let me check quickly what's the issue

**Comment by R3dIO** [comment]
@tatirajurishabh I have checked and fixed the API endpoint try it now

**Comment by tatirajurishabh** [comment]
Moving it to next Sprint as implementing the API call is breaking the UI. Will require more thought into this.

**Comment by tatirajurishabh** [comment]
Closing as it is completed
