### ISSUE TITLE
User should be able to see posts on their homescreen

### ISSUE THREAD

**Issue by valasaladinesh** [RTX2080-UF/gatorshare-frontend#9]

**Comment by tatirajurishabh** [comment]
For now, we are going with a simple list of posts. Eventually over the future sprints the filtering by recommendation / interest will be done.

**Comment by tatirajurishabh** [comment]
This story has the following tasks:
#15 
#16 
#17 
#18 
#19

**Comment by tatirajurishabh** [comment]
Merged the PR. Closing issue.
